name: FastAPI CI/CD with Docker Compose

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: bestbest/be-facefindr:1.0.0
  DEPLOY_SERVER: 119.59.99.192
  DEPLOY_USER: root
  DEPLOY_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: bestbest

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE .

    - name: Push Docker image to Docker Hub
      run: docker push $DOCKER_IMAGE

  deploy:
        name: Deploy to Server
        runs-on: ubuntu-latest
        needs: build_and_push

        steps:
        - name: Install sshpass
          run: sudo apt-get update && sudo apt-get install -y sshpass

        - name: Deploy Server .
          run: |
            export SSHPASS=$DEPLOY_PASSWORD
            sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "
              docker image prune -a -f
              docker pull \"$DOCKER_IMAGE\"
              
              # Stop and remove old container if it exists
              docker stop be-facefinder || true
              docker rm be-facefinder || true
              
              mkdir -p /root/face-finder/uploads /root/face-finder/results
              mkdir -p /root/face-finder/db
              touch /root/face-finder/db/facedb.sqlite
              chmod -R 777 /root/face-finder
              docker run -d -p 9999:8000 \
                -v /root/face-finder/uploads:/app/uploads \
                -v /root/face-finder/results:/app/results \
                -v /root/face-finder/db/facedb.sqlite:/app/facedb.sqlite \
                -e SERVER_BASE_URL=https://facefindr.api.thetigerteamacademy.net \
                --name be-facefinder \"$DOCKER_IMAGE\"
            "
